filter:
    excluded_paths:
        - "backend/coverage/"               # ignore coverage folder
build:
  nodes:
    coverage:
      tests:
        override:
          - command: "cd backend/ && npm install --save-dev && && npm test"
            coverage:
              file: backend/coverage/clover.xml   # <- Set this to where we find the coverage data.
              format: clover
