build:
  nodes:
    coverage:
      tests:
        paths:
          - "./tests"
      environment:
        PATH_COVERAGE: "./coverage/clover.xml"
      overrides:
        - command: ./test.sh
          coverage:
            file: "./coverage/clover.xml"
            format: "clover"

filter:
  excluded_paths: [coverage/*]
