build:
    nodes:
        analysis:
            environment:
                php:
                    version: 7.4
                node:
                    version: 14

    tests:
        override:
            - |
                nvm install 16.13.0
                nvm use 16.13.0
                npm install
                npm run test  # Replace 'test' with the npm script that runs your Jest tests
                npm run coverage  # Replace 'coverage' with the npm script that generates your report
            - command: 'scrutinizer-clover coverage/lcov.info'
            
filter:
  excluded_paths: [coverage/*]
