checks:
    javascript: true

build:
    environment:
        node: "16"

    nodes:
        analysis:
            tests:
                override:
                    - js-scrutinizer-run
        tests: true
filter:
    excluded_paths:
        - "backend/coverage/lcov-report"
