checks:
    javascript: true

build:
    environment:
        node: "16"

    nodes:
        coverage:
            dependencies:
                before:
                    - cd backend
                    - sudo apt-get update # Update package lists
                    - sudo apt-get install -y gcc-4.9 g++-4.9 # Install gcc and g++
                    - update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-4.9 60 --slave /usr/bin/g++ g++ /usr/bin/g++-4.9
                    - npm install
            tests:
                override:
                    - command: "npm test"
                      coverage:
                          file: "backend/coverage/clover.xml"
                          format: clover
        analysis:
            tests:
                override:
                    - js-scrutinizer-run
        tests: true
filter:
    excluded_paths:
        - "backend/coverage/lcov-report"
