checks:
    javascript: true

build:
    environment:
        node: "14"

    nodes:
        coverage:
            dependencies:
                before:
                    - nvm install 14
                    - nvm use 14
                    - cd backend
                    - npm install
            tests:
                override:
                    - command: "npm test"
                      coverage:
                          file: "backend/coverage/clover.xml"
                          format: clover
        analysis:
            tests:
                override:
                    - js-scrutinizer-run
        tests: true
filter:
    excluded_paths:
        - "backend/coverage/lcov-report"
