version: '3.8'

services:
  app:
    container_name: scooter
    build:
      context: .
      dockerfile: ./frontend/Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./frontend/scooter:/app

    stdin_open: true
    tty: true

  db:
    container_name: scooter_db
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    ports:
      - "1337:1337"
    volumes:
      - ./backend:/app
    stdin_open: true
    tty: true

volumes:
  mysql_data: {}
