version: '3.8'

services:
  mysql:
    image: "mysql:latest"
    restart: always
    ports: 
      - "13306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD="password"
    volumes:
     - ./backend/databases/sql:/docker-entrypoint-initdb.d
  mysql_client:
    image: "mysql:latest"


  app:
    container_name: scooter
    build:
      context: .
      dockerfile: ./frontend/Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./frontend/scooter:/app

    stdin_open: true
    tty: true

volumes:
  mysql_data: {}