version: "3.8"

services:
  frontend:
    container_name: boi_frontend
    build:
      context: .
      dockerfile: ./frontend/Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./frontend/scooter:/frontend
    stdin_open: true
    tty: true
  backend:
    container_name: boi_backend
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    ports:
      - "1337:1337"
    volumes:
      - ./backend/:/backend
    stdin_open: true
    tty: true

