name: Node.js CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: Install Dependencies
      run: |
        cd frontend/scooter
        npm ci
    - name: Build
      run: |
        cd frontend/scooter
        npm run build --if-present
    - name: Run Tests
      run: |
        cd frontend/scooter
        npm test
    - name: Install backend Dependencies
      run: |
        cd backend
        npm ci
    - name: Start Backend server for testing
      run: |
        docker compose up -d backend
    - name: Run backend tests
      run: |
        cd backend
        npm test
